#!/bin/bash
# Requires imagemagick (sudo apt-get install imagemagick on ubuntu)
# This script resizes all of a given type of image to the size specified
# $1 is the first argument given to the script; $2 is the second
# $1 should be the new pixel size needed (ex: 25x25)
# $2 should be the type of image file that should be converted
# example usage: ./resize 15x15 png 

curDir=`pwd`
for file in `ls`
do 
  ext=${file##*.}	
  if [ $ext == $2 ]
  then 
    convert $file -resize $1 $file
  fi
done
